project:
  type: website

website:
  title: "Benedetta Gasbarra"
  navbar:
    right:
      - href: index.qmd
        text: Home
        
      - href: Projects.qmd
        text: Projects
        
      - href: courses.qmd
        text: Relvant Courses
        
      - href: education.qmd
        text: Education
        

  page-footer:
    center: "Â© Copyright 2024 Benedetta Gasbarra"      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto

